apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: luizholandadocker/client
          context: client
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: 'src/**/*.js'
                  dest: .
        - image: luizholandadocker/comments
          context: comments
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: luizholandadocker/event-but
          context: event-bus
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: luizholandadocker/moderation
          context: moderation
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: luizholandadocker/posts
          context: posts
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: luizholandadocker/query
          context: query
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .